name: Run Pipeline

on:
  schedule:
    - cron: '0 12 * * *'  # Everyday at 12:00 UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TEST_ENV: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm bertopic pymongo python-dotenv scikit-learn nltk transformers torch datasets

    - name: Run pipeline script
      run: bash news/run_pipeline.sh
