name: Run Pipeline

on:
  schedule:
    - cron: '00 16 * * *'  # Everyday at 16:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TEST_ENV: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm bertopic pymongo python-dotenv scikit-learn nltk transformers torch datasets

    - name: Run pipeline script
      run: |
        chmod +x news/run_pipeline.sh
        bash news/run_pipeline.sh
